/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User;

import LoginRegister.Login;
import config.Session;
import config.dbConnect;
import java.awt.Color;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;


/**
 *
 * @author CYBER SECURITY
 */
public class adoptionForm extends javax.swing.JFrame {
     
    /**
     * Creates new form adminDashboard
     */ 
       

    public adoptionForm() {
        initComponents();
        this.setLocationRelativeTo(null); // Make Jframe Center allighnment
         DateTimeFormatter dtf = DateTimeFormatter.ofPattern("MM/dd/yyyy");
         LocalDate localDate = LocalDate.now();
        
         adate.setText(""+dtf.format(localDate));
       
        
    } 
    
      boolean checkadd = true;
                  
       Color hc=new Color( 0,10,48);
       Color nc=new Color(0,152,153);
      
        

    
          
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        Uback = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        body = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        atable = new javax.swing.JTable();
        header6 = new javax.swing.JPanel();
        U_id = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        U_id3 = new javax.swing.JLabel();
        pid = new javax.swing.JTextField();
        U_id4 = new javax.swing.JLabel();
        U_id5 = new javax.swing.JLabel();
        U_id6 = new javax.swing.JLabel();
        adate = new javax.swing.JTextField();
        U_id7 = new javax.swing.JLabel();
        astatus = new javax.swing.JComboBox<>();
        U_id8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        add2 = new javax.swing.JPanel();
        add1 = new javax.swing.JPanel();
        add = new javax.swing.JPanel();
        addlabel = new javax.swing.JLabel();
        update = new javax.swing.JPanel();
        addlabel2 = new javax.swing.JLabel();
        delete = new javax.swing.JPanel();
        addlabel3 = new javax.swing.JLabel();
        ptype = new javax.swing.JComboBox<>();
        header1 = new javax.swing.JPanel();

        header.setBackground(new java.awt.Color(204, 204, 204));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        Uback.setBackground(new java.awt.Color(153, 153, 255));
        Uback.setForeground(new java.awt.Color(5, 92, 157));
        Uback.setPreferredSize(new java.awt.Dimension(760, 60));
        Uback.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BACK");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        Uback.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 60, 60));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("ADOPTION FORM");
        Uback.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 170, 60));

        getContentPane().add(Uback);
        Uback.setBounds(0, 0, 760, 60);

        body.setBackground(new java.awt.Color(0, 10, 48));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        body.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        atable.setBackground(new java.awt.Color(0,0,0,60));
        atable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        atable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(atable);

        body.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 60, -1, 220));

        header6.setBackground(new java.awt.Color(0, 152, 153));
        header6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        U_id.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        U_id.setForeground(new java.awt.Color(255, 255, 255));
        U_id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        U_id.setText("ID");
        U_id.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        U_id.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                U_idMouseClicked(evt);
            }
        });
        header6.add(U_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 130, 40));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user-removebg-preview (1).png"))); // NOI18N
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        header6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 100));

        U_id3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        U_id3.setForeground(new java.awt.Color(255, 255, 255));
        U_id3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        U_id3.setText("Current User ID");
        U_id3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        U_id3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                U_id3MouseClicked(evt);
            }
        });
        header6.add(U_id3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 130, 40));

        body.add(header6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, -1));

        pid.setText(" ");
        pid.setEnabled(false);
        body.add(pid, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 160, 40));

        U_id4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        U_id4.setForeground(new java.awt.Color(255, 255, 255));
        U_id4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/addsss__1_-removebg-preview (1).png"))); // NOI18N
        U_id4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        U_id4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                U_id4MouseClicked(evt);
            }
        });
        body.add(U_id4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 50, 60));

        U_id5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        U_id5.setForeground(new java.awt.Color(255, 255, 255));
        U_id5.setText("Pet Type:");
        U_id5.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        U_id5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                U_id5MouseClicked(evt);
            }
        });
        body.add(U_id5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 130, 40));

        U_id6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        U_id6.setForeground(new java.awt.Color(255, 255, 255));
        U_id6.setText("Date:");
        U_id6.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        U_id6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                U_id6MouseClicked(evt);
            }
        });
        body.add(U_id6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 130, 40));

        adate.setText(" ");
        adate.setEnabled(false);
        body.add(adate, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, 160, 40));

        U_id7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        U_id7.setForeground(new java.awt.Color(255, 255, 255));
        U_id7.setText("Adoption Status:");
        U_id7.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        U_id7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                U_id7MouseClicked(evt);
            }
        });
        body.add(U_id7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, 130, 40));

        astatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "Approved", " " }));
        astatus.setEnabled(false);
        body.add(astatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, 160, 40));

        U_id8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        U_id8.setForeground(new java.awt.Color(255, 255, 255));
        U_id8.setText("Pet Id:");
        U_id8.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        U_id8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                U_id8MouseClicked(evt);
            }
        });
        body.add(U_id8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 130, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("ADOPTION TABLE");
        body.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 170, 60));

        add2.setBackground(new java.awt.Color(0, 152, 153));
        add2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                add2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                add2MouseExited(evt);
            }
        });
        add2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        body.add(add2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 160, 90));

        add1.setBackground(new java.awt.Color(0, 152, 153));
        add1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                add1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                add1MouseExited(evt);
            }
        });
        add1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        body.add(add1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 130, 60));

        add.setBackground(new java.awt.Color(0, 152, 153));
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addMouseExited(evt);
            }
        });
        add.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addlabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        addlabel.setForeground(new java.awt.Color(255, 255, 255));
        addlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addlabel.setText("ADD");
        addlabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        addlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addlabelMouseClicked(evt);
            }
        });
        add.add(addlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 50, 10));

        body.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 130, 30));

        update.setBackground(new java.awt.Color(0, 152, 153));
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateMouseExited(evt);
            }
        });
        update.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addlabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        addlabel2.setForeground(new java.awt.Color(255, 255, 255));
        addlabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addlabel2.setText("UPDATE");
        addlabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        addlabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addlabel2MouseClicked(evt);
            }
        });
        update.add(addlabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 60, 10));

        body.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 130, 30));

        delete.setBackground(new java.awt.Color(0, 152, 153));
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteMouseExited(evt);
            }
        });
        delete.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addlabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        addlabel3.setForeground(new java.awt.Color(255, 255, 255));
        addlabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addlabel3.setText("DELETE");
        addlabel3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        addlabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addlabel3MouseClicked(evt);
            }
        });
        delete.add(addlabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 60, 10));

        body.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 130, 30));

        ptype.setBackground(new java.awt.Color(204, 204, 204));
        ptype.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ptype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Dog", " ", "German Dog", "Austillian Dog", "Bulldog", "Labrador Retriever", "Golden Retriever", "Beagle", "Poodle", "Chihuahua" }));
        ptype.setEnabled(false);
        ptype.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ptypeMouseClicked(evt);
            }
        });
        body.add(ptype, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 160, 40));

        getContentPane().add(body);
        body.setBounds(0, 60, 760, 420);

        header1.setBackground(new java.awt.Color(204, 204, 204));
        header1.setLayout(null);
        getContentPane().add(header1);
        header1.setBounds(0, 0, 760, 50);

        setSize(new java.awt.Dimension(770, 520));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
               
    
    
    
    
    
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
           
      
        UsersDashboard adb = new UsersDashboard();
        adb.setVisible(true);
        this.dispose();
    
             
    }//GEN-LAST:event_jLabel1MouseClicked

    private void U_idMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_U_idMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_U_idMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
        Session ses = Session.getInstance();
       
        
        if (ses.getA_id()==0){
           JOptionPane.showMessageDialog(null,"No accout verefied, Login first!");
           Login lg = new Login();
           lg.setVisible(true);
           this.dispose();
        }else{
            
       
    } 
        
        
    }//GEN-LAST:event_formWindowActivated

    private void addlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addlabelMouseClicked
        
    }//GEN-LAST:event_addlabelMouseClicked

    private void addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseEntered
        
        
       
        
        add.setBackground(nc);
    }//GEN-LAST:event_addMouseEntered

    private void addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseExited
        add.setBackground(hc);
    }//GEN-LAST:event_addMouseExited

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
 
          Session ses = Session.getInstance();
           dbConnect dbc=new dbConnect();

        if (pid.getText().isEmpty() || ptype.getSelectedIndex()==1
            || adate.getText().isEmpty()
            || astatus.getSelectedIndex()==1  ){
          JOptionPane.showMessageDialog(null, "All fields  are Required");
           
      }else{
           if (dbc.insertData("INSERT INTO adoption(a_id, p_id, date, a_status)VALUES('" + ses.getA_id() + "',"
        + "'" + pid.getText() + "',"
        + "'" + adate.getText() + "',"
        + "'" + astatus.getSelectedItem() + "')") > 0) { // Changed '== 0' to '> 0'
    JOptionPane.showMessageDialog(null, "Adoption Record added Successfully!");
}
        
        
    }//GEN-LAST:event_addMouseClicked
    }
    private void atableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atableMouseClicked
         
    }//GEN-LAST:event_atableMouseClicked

    private void addlabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addlabel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_addlabel2MouseClicked

    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked
            
               
    }//GEN-LAST:event_updateMouseClicked

    private void updateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseEntered
      
         update.setBackground(nc);
    }//GEN-LAST:event_updateMouseEntered

    private void updateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseExited
         update.setBackground(hc);
    }//GEN-LAST:event_updateMouseExited

    private void addlabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addlabel3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_addlabel3MouseClicked

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteMouseClicked

    private void deleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseEntered
          delete.setBackground(nc);
    }//GEN-LAST:event_deleteMouseEntered

    private void deleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseExited
        delete.setBackground(hc);
    }//GEN-LAST:event_deleteMouseExited

    private void U_id3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_U_id3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_U_id3MouseClicked

    private void U_id4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_U_id4MouseClicked
         
        this.dispose();
        petTable pt = new petTable();
        pt.setVisible(true);
        
    }//GEN-LAST:event_U_id4MouseClicked

    private void U_id5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_U_id5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_U_id5MouseClicked

    private void U_id6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_U_id6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_U_id6MouseClicked

    private void U_id7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_U_id7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_U_id7MouseClicked

    private void U_id8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_U_id8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_U_id8MouseClicked

    private void add1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_add1MouseClicked

    private void add1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_add1MouseEntered

    private void add1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_add1MouseExited

    private void add2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_add2MouseClicked

    private void add2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_add2MouseEntered

    private void add2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_add2MouseExited

    private void ptypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ptypeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ptypeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adoptionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adoptionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adoptionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adoptionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adoptionForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel U_id;
    private javax.swing.JLabel U_id3;
    private javax.swing.JLabel U_id4;
    private javax.swing.JLabel U_id5;
    private javax.swing.JLabel U_id6;
    private javax.swing.JLabel U_id7;
    private javax.swing.JLabel U_id8;
    private javax.swing.JPanel Uback;
    private javax.swing.JTextField adate;
    private javax.swing.JPanel add;
    private javax.swing.JPanel add1;
    private javax.swing.JPanel add2;
    private javax.swing.JLabel addlabel;
    private javax.swing.JLabel addlabel2;
    private javax.swing.JLabel addlabel3;
    private javax.swing.JComboBox<String> astatus;
    private javax.swing.JTable atable;
    private javax.swing.JPanel body;
    private javax.swing.JPanel delete;
    private javax.swing.JPanel header;
    private javax.swing.JPanel header1;
    private javax.swing.JPanel header6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTextField pid;
    public javax.swing.JComboBox<String> ptype;
    private javax.swing.JPanel update;
    // End of variables declaration//GEN-END:variables
}
