/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User;

import LoginRegister.Login;
import config.Session;
import javax.swing.JOptionPane;


/**
 *
 * @author CYBER SECURITY
 */
public class UsersDashboard extends javax.swing.JFrame {

    /**
     * Creates new form UsersDashboard
     */
    public UsersDashboard() {
        initComponents();
           this.setLocationRelativeTo(null); // Make Jframe Center allighnment
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        header2 = new javax.swing.JPanel();
        account = new javax.swing.JLabel();
        Ausers = new javax.swing.JLabel();
        Pets1 = new javax.swing.JLabel();
        Adoption1 = new javax.swing.JLabel();
        location = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Acc_ulname = new javax.swing.JLabel();
        Acc_uname = new javax.swing.JLabel();
        header6 = new javax.swing.JPanel();
        header7 = new javax.swing.JPanel();
        header10 = new javax.swing.JPanel();
        header8 = new javax.swing.JPanel();
        header9 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header1.setBackground(new java.awt.Color(0, 48, 96));
        header1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LOGOUT");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        header1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, -4, 110, 70));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("USER DASHBOARD");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        header1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 60));

        getContentPane().add(header1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 60));

        header2.setBackground(new java.awt.Color(5, 92, 157));
        header2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        account.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        account.setForeground(new java.awt.Color(255, 255, 255));
        account.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        account.setText("Account");
        account.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        account.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountMouseClicked(evt);
            }
        });
        header2.add(account, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 100, 40));

        Ausers.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Ausers.setForeground(new java.awt.Color(255, 255, 255));
        Ausers.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Ausers.setText("Users");
        Ausers.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Ausers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AusersMouseClicked(evt);
            }
        });
        header2.add(Ausers, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 100, 40));

        Pets1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Pets1.setForeground(new java.awt.Color(255, 255, 255));
        Pets1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Pets1.setText("Pets");
        Pets1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Pets1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pets1MouseClicked(evt);
            }
        });
        header2.add(Pets1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 100, 40));

        Adoption1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Adoption1.setForeground(new java.awt.Color(255, 255, 255));
        Adoption1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Adoption1.setText("Adoption");
        Adoption1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Adoption1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Adoption1MouseClicked(evt);
            }
        });
        header2.add(Adoption1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 100, 40));

        location.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        location.setForeground(new java.awt.Color(255, 255, 255));
        location.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        location.setText("Location");
        location.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        location.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                locationMouseClicked(evt);
            }
        });
        header2.add(location, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 100, 40));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user-removebg-preview (1).png"))); // NOI18N
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        header2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 110));

        Acc_ulname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Acc_ulname.setForeground(new java.awt.Color(255, 255, 255));
        Acc_ulname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Acc_ulname.setText("LastName:");
        Acc_ulname.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        header2.add(Acc_ulname, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 140, 40));

        Acc_uname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Acc_uname.setForeground(new java.awt.Color(255, 255, 255));
        Acc_uname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Acc_uname.setText("FirstName:");
        Acc_uname.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        header2.add(Acc_uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 140, 40));

        getContentPane().add(header2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 140, 420));

        header6.setBackground(new java.awt.Color(126, 200, 227));
        header6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header7.setBackground(new java.awt.Color(0, 12, 102));
        header7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header10.setBackground(new java.awt.Color(102, 102, 255));
        header10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        header7.add(header10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 570, 190));

        header8.setBackground(new java.awt.Color(102, 102, 255));
        header8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        header7.add(header8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 120, 90));

        header9.setBackground(new java.awt.Color(102, 102, 255));
        header9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        header7.add(header9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 120, 90));

        header6.add(header7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 590, 400));

        getContentPane().add(header6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 620, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
                 Login lg = new Login();
        lg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void accountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountMouseClicked


    }//GEN-LAST:event_accountMouseClicked

    private void Pets1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pets1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Pets1MouseClicked

    private void Adoption1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Adoption1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Adoption1MouseClicked

    private void locationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_locationMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_locationMouseClicked

    private void AusersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AusersMouseClicked
         
    }//GEN-LAST:event_AusersMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Session ses = Session.getInstance();
       
        
        if (ses.getA_id()==0){
           JOptionPane.showMessageDialog(null,"No accout verefied, Login first!");
           Login lg = new Login();
           lg.setVisible(true);
           this.dispose();
        }else{
            
       Acc_uname.setText(""+ses.getFirstame());
        Acc_ulname.setText(""+ses.getLastnmae());
    } 
        
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsersDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsersDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsersDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsersDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsersDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Acc_ulname;
    private javax.swing.JLabel Acc_uname;
    private javax.swing.JLabel Adoption1;
    private javax.swing.JLabel Ausers;
    private javax.swing.JLabel Pets1;
    private javax.swing.JLabel account;
    private javax.swing.JPanel header1;
    private javax.swing.JPanel header10;
    private javax.swing.JPanel header2;
    private javax.swing.JPanel header6;
    private javax.swing.JPanel header7;
    private javax.swing.JPanel header8;
    private javax.swing.JPanel header9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel location;
    // End of variables declaration//GEN-END:variables
}
