/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import static LoginRegister.Register.email;
import static LoginRegister.Register.usname;
import config.dbConnect;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author CYBER SECURITY
 */
public class AddUsersForm extends javax.swing.JFrame {

    /**
     * Creates new form AddUsersForm
     */
    public AddUsersForm() {
        initComponents();
    }
        public boolean duplicateCheck(){
          dbConnect dbc =  new dbConnect();
          try{
              String query = "SELECT * FROM accounts WHERE username ='"+uname.getText()+ "' OR  email = '"+em.getText()+"'";
                ResultSet resultSet = dbc.getData(query);
              
                 if (resultSet.next()){
                     email=resultSet.getString("email");
                        if(email.equals(em.getText())){
                             JOptionPane.showMessageDialog(null,"Email is already used!");
                             em.setText("");  
                             return true;}
                             usname=resultSet.getString("username");
                          if(usname.equals(uname.getText())){
                             JOptionPane.showMessageDialog(null,"Username is already used!");}
                             uname.setText("");
                           return true;}
                 else{
                         return false;}
                
                }catch(SQLException ex){
                  System.out.println("" + ex);
                     return false;
                 }
      
      }  
        
        
          public boolean updateCheck(){
              
          dbConnect dbc =  new dbConnect();
          try{
              String query = "SELECT * FROM accounts WHERE (username ='"+uname.getText()+ "' OR  email = '"+em.getText()+"') AND a_id!= '"+u_id.getText()+"'";
                ResultSet resultSet = dbc.getData(query);
              
                 if (resultSet.next()){
                     email=resultSet.getString("email");
                        if(email.equals(em.getText())){
                             JOptionPane.showMessageDialog(null,"Email is already used!");
                             em.setText("");  
                             return true;}
                        
                             usname=resultSet.getString("username");
                          if(usname.equals(uname.getText())){
                             JOptionPane.showMessageDialog(null,"Username is already used!");}
                             uname.setText("");
                           return true;}
                 else{
                         return false;}
                
                }catch(SQLException ex){
                  System.out.println("" + ex);
                     return false;
                 }
      
      }  
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Uback = new javax.swing.JPanel();
        Unavbar = new javax.swing.JPanel();
        lastname = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        jpanelEmail = new javax.swing.JLabel();
        em = new javax.swing.JTextField();
        username1 = new javax.swing.JLabel();
        uname = new javax.swing.JTextField();
        username = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        usertype = new javax.swing.JLabel();
        firstname = new javax.swing.JLabel();
        utype = new javax.swing.JComboBox<>();
        fname = new javax.swing.JTextField();
        ustatus = new javax.swing.JComboBox<>();
        User_status = new javax.swing.JLabel();
        uid = new javax.swing.JLabel();
        u_id = new javax.swing.JTextField();
        u_add = new javax.swing.JButton();
        u_update = new javax.swing.JButton();
        u_delete = new javax.swing.JButton();
        u_refresh = new javax.swing.JButton();
        u_clear = new javax.swing.JButton();
        u_cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Uback.setBackground(new java.awt.Color(5, 92, 147));
        Uback.setForeground(new java.awt.Color(5, 92, 157));
        Uback.setPreferredSize(new java.awt.Dimension(760, 60));
        Uback.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Unavbar.setBackground(new java.awt.Color(0,0,0,60));
        Unavbar.setForeground(new java.awt.Color(102, 102, 102));
        Unavbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lastname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lastname.setForeground(new java.awt.Color(255, 255, 255));
        lastname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lastname.setText("Last Name:");
        Unavbar.add(lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        lname.setBackground(new java.awt.Color(204, 204, 204));
        lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameActionPerformed(evt);
            }
        });
        Unavbar.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 230, -1));

        jpanelEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jpanelEmail.setForeground(new java.awt.Color(255, 255, 255));
        jpanelEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jpanelEmail.setText("Email:");
        Unavbar.add(jpanelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        em.setBackground(new java.awt.Color(204, 204, 204));
        em.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emActionPerformed(evt);
            }
        });
        Unavbar.add(em, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 280, -1));

        username1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        username1.setForeground(new java.awt.Color(255, 255, 255));
        username1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        username1.setText("Username:");
        Unavbar.add(username1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, -1));

        uname.setBackground(new java.awt.Color(204, 204, 204));
        uname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unameActionPerformed(evt);
            }
        });
        Unavbar.add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 230, -1));

        username.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        username.setText("Password:");
        Unavbar.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 90, 20));

        password.setBackground(new java.awt.Color(204, 204, 204));
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        Unavbar.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 280, -1));

        usertype.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        usertype.setForeground(new java.awt.Color(255, 255, 255));
        usertype.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usertype.setText("UserType:");
        Unavbar.add(usertype, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, 20));

        firstname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        firstname.setForeground(new java.awt.Color(255, 255, 255));
        firstname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        firstname.setText("First Name:");
        Unavbar.add(firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        utype.setBackground(new java.awt.Color(204, 204, 204));
        utype.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        utype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select UserType", "User", "Admin" }));
        Unavbar.add(utype, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 230, -1));

        fname.setBackground(new java.awt.Color(204, 204, 204));
        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });
        Unavbar.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 230, -1));

        ustatus.setBackground(new java.awt.Color(204, 204, 204));
        ustatus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ustatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Pending" }));
        Unavbar.add(ustatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 230, -1));

        User_status.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        User_status.setForeground(new java.awt.Color(255, 255, 255));
        User_status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        User_status.setText("User Status:");
        Unavbar.add(User_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, -1, 20));

        uid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        uid.setForeground(new java.awt.Color(255, 255, 255));
        uid.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        uid.setText("User ID:");
        Unavbar.add(uid, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 100, -1));

        u_id.setBackground(new java.awt.Color(204, 204, 204));
        u_id.setEnabled(false);
        u_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                u_idActionPerformed(evt);
            }
        });
        Unavbar.add(u_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 230, -1));

        Uback.add(Unavbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 540, 360));

        u_add.setBackground(new java.awt.Color(0, 204, 255));
        u_add.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        u_add.setForeground(new java.awt.Color(255, 255, 255));
        u_add.setText("ADD");
        u_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                u_addActionPerformed(evt);
            }
        });
        Uback.add(u_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 140, 50));

        u_update.setBackground(new java.awt.Color(0, 204, 255));
        u_update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        u_update.setForeground(new java.awt.Color(255, 255, 255));
        u_update.setText("UPDATE");
        u_update.setEnabled(false);
        u_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                u_updateActionPerformed(evt);
            }
        });
        Uback.add(u_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 140, 50));

        u_delete.setBackground(new java.awt.Color(0, 204, 255));
        u_delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        u_delete.setForeground(new java.awt.Color(255, 255, 255));
        u_delete.setText("DELETE");
        u_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                u_deleteActionPerformed(evt);
            }
        });
        Uback.add(u_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 140, 50));

        u_refresh.setBackground(new java.awt.Color(0, 204, 255));
        u_refresh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        u_refresh.setForeground(new java.awt.Color(255, 255, 255));
        u_refresh.setText("REFRESH");
        u_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                u_refreshActionPerformed(evt);
            }
        });
        Uback.add(u_refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 140, 50));

        u_clear.setBackground(new java.awt.Color(0, 204, 255));
        u_clear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        u_clear.setForeground(new java.awt.Color(255, 255, 255));
        u_clear.setText("CLEAR");
        u_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                u_clearActionPerformed(evt);
            }
        });
        Uback.add(u_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 140, 50));

        u_cancel.setBackground(new java.awt.Color(0, 204, 255));
        u_cancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        u_cancel.setForeground(new java.awt.Color(255, 255, 255));
        u_cancel.setText("CANCEl");
        u_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                u_cancelActionPerformed(evt);
            }
        });
        Uback.add(u_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 140, 50));

        getContentPane().add(Uback, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 780, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameActionPerformed

    private void emActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emActionPerformed

    }//GEN-LAST:event_emActionPerformed

    private void unameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unameActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed

    }//GEN-LAST:event_passwordActionPerformed

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed

    private void u_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_u_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_u_idActionPerformed

    private void u_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_u_updateActionPerformed
      
        
        if

        (fname.getText().isEmpty() || lname.getText().isEmpty()
            || em.getText().isEmpty()
            || utype.getSelectedIndex()==0
            || uname.getText().isEmpty()
            || password.getText().isEmpty() ){
            JOptionPane.showMessageDialog(null,"All fields are required!"); //validation for register...

            return ;

        }else if (password.getText().length()< 8){
            JOptionPane.showMessageDialog(null," Password should contain atleast 8 character above!");
            password.setText("");
            return;}

        String email = this.em.getText();
        String emailRegex = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$";
        Pattern patternEmail = Pattern.compile(emailRegex);
        Matcher matcherEmail = patternEmail.matcher(email);

        if (!matcherEmail.matches()) {
            JOptionPane.showMessageDialog(this, "Invalid email format. Please use a valid email address.", "Error", JOptionPane.ERROR_MESSAGE);
            this.em.setText("");
            this.em.requestFocus();

        }

        else if(updateCheck()){ 
            System.out.println("Duplicate Exist!");
        }else{
        
        
        dbConnect dbc = new dbConnect();
        dbc.updateData("UPDATE accounts SET firstname='"+fname.getText()+"',lastname ='"+lname.getText()+"',email ='"+em.getText()+"',type ='"+utype.getSelectedItem()+"',username ='"+uname.getText()+"',"
                + "status ='"+ustatus.getSelectedItem()+"' WHERE a_id = '"+u_id.getText()+"'  ");
        
                
        UsersForm uf= new UsersForm();
        uf.setVisible(true);
        this.dispose();
    }
        
    }//GEN-LAST:event_u_updateActionPerformed

    private void u_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_u_deleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_u_deleteActionPerformed

    private void u_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_u_refreshActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_u_refreshActionPerformed

    private void u_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_u_clearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_u_clearActionPerformed

    private void u_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_u_cancelActionPerformed
      UsersForm uf = new UsersForm();
      uf.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_u_cancelActionPerformed

    private void u_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_u_addActionPerformed

        dbConnect dbc=new dbConnect();

        if

        (fname.getText().isEmpty() || lname.getText().isEmpty()
            || em.getText().isEmpty()
            || utype.getSelectedIndex()==0
            || uname.getText().isEmpty()
            || password.getText().isEmpty() ){
            JOptionPane.showMessageDialog(null,"All fields are required!");  

            return ;

        }else if (password.getText().length()< 8){
            JOptionPane.showMessageDialog(null," Password should contain atleast 8 character above!");
            password.setText("");
            return;}

        String email = this.em.getText();
        String emailRegex = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$";
        Pattern patternEmail = Pattern.compile(emailRegex);
        Matcher matcherEmail = patternEmail.matcher(email);

        if (!matcherEmail.matches()) {
            JOptionPane.showMessageDialog(this, "Invalid email format. Please use a valid email address.", "Error", JOptionPane.ERROR_MESSAGE);
            this.em.setText("");
            this.em.requestFocus();

        }

        else if(duplicateCheck()){
            System.out.println("Duplicate Exist!");

        }
        else if (dbc. insertData("INSERT INTO accounts(firstname, lastname, email, type, username, password, status) "
            + "VALUES('"+fname.getText()+"',"
            + "'"+lname.getText()+"',"
            + "'"+this.em.getText()+"',"
            + "'"+utype.getSelectedItem()+"',"
            + "'"+uname.getText()+"',"
            + "'"+ password.getText()+"','"+ustatus.getSelectedItem()+"')") ==1)

    {
        JOptionPane.showMessageDialog(null, " User Succesfully Added");
        UsersForm uf= new UsersForm();
        uf.setVisible(true);
        this.dispose();

        } else {
            JOptionPane.showMessageDialog(null,"Connection error!!");
        }
    }//GEN-LAST:event_u_addActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddUsersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddUsersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddUsersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddUsersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddUsersForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Uback;
    private javax.swing.JPanel Unavbar;
    private javax.swing.JLabel User_status;
    public javax.swing.JTextField em;
    private javax.swing.JLabel firstname;
    public javax.swing.JTextField fname;
    private javax.swing.JLabel jpanelEmail;
    private javax.swing.JLabel lastname;
    public javax.swing.JTextField lname;
    public javax.swing.JPasswordField password;
    public javax.swing.JButton u_add;
    private javax.swing.JButton u_cancel;
    private javax.swing.JButton u_clear;
    private javax.swing.JButton u_delete;
    public javax.swing.JTextField u_id;
    private javax.swing.JButton u_refresh;
    public javax.swing.JButton u_update;
    private javax.swing.JLabel uid;
    public javax.swing.JTextField uname;
    private javax.swing.JLabel username;
    private javax.swing.JLabel username1;
    private javax.swing.JLabel usertype;
    public javax.swing.JComboBox<String> ustatus;
    public javax.swing.JComboBox<String> utype;
    // End of variables declaration//GEN-END:variables
}
