/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;




/**
 *
 * @author CYBER SECURITY
 */
public class AdminDashboard extends javax.swing.JFrame {

    /**
     * Creates new form usersTable
     */
    public AdminDashboard() {
        initComponents();
         this.setLocationRelativeTo(null); // Make Jframe Center allighnment
        
      
    }
   
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        navbar = new javax.swing.JPanel();
        users = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Adoption = new javax.swing.JButton();
        header1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Alogout = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        body.add(jPanel3);
        jPanel3.setBounds(0, 0, 0, 0);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        navbar.setBackground(new java.awt.Color(0, 102, 102));
        navbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        users.setBackground(new java.awt.Color(0, 51, 255));
        users.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        users.setForeground(new java.awt.Color(255, 255, 255));
        users.setText("USERS");
        users.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usersActionPerformed(evt);
            }
        });
        navbar.add(users, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 120, 60));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user-removebg-preview (1).png"))); // NOI18N
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        navbar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 170, 140));

        jLabel1.setBackground(new java.awt.Color(153, 153, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/animal_shelter-removebg-preview (1) (1).png"))); // NOI18N
        jLabel1.setFocusable(false);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        navbar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 160, 160));

        Adoption.setBackground(new java.awt.Color(0, 51, 255));
        Adoption.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Adoption.setForeground(new java.awt.Color(255, 255, 255));
        Adoption.setText("ADOPTION");
        Adoption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdoptionActionPerformed(evt);
            }
        });
        navbar.add(Adoption, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 110, 60));

        getContentPane().add(navbar);
        navbar.setBounds(170, 50, 450, 370);

        header1.setBackground(new java.awt.Color(204, 204, 204));
        header1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("ADMIN DASHBOARD");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        header1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 50));

        Alogout.setBackground(new java.awt.Color(204, 204, 204));
        Alogout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Alogout.setText("LOGOUT");
        Alogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AlogoutMouseClicked(evt);
            }
        });
        Alogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlogoutActionPerformed(evt);
            }
        });
        header1.add(Alogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(519, 6, 100, 40));

        getContentPane().add(header1);
        header1.setBounds(0, 0, 620, 50);

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ADMIN");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 170, 40));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoAdmin (6).png"))); // NOI18N
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 180));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 50, 170, 370);

        setSize(new java.awt.Dimension(636, 459));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usersActionPerformed
       UsersForm adb = new UsersForm();
                adb.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_usersActionPerformed

    private void AdoptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdoptionActionPerformed
      
    }//GEN-LAST:event_AdoptionActionPerformed

    private void AlogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AlogoutMouseClicked

    }//GEN-LAST:event_AlogoutMouseClicked

    private void AlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlogoutActionPerformed

    }//GEN-LAST:event_AlogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Adoption;
    private javax.swing.JButton Alogout;
    private javax.swing.JPanel body;
    private javax.swing.JPanel header1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel navbar;
    private javax.swing.JButton users;
    // End of variables declaration//GEN-END:variables
}
