/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import static admin.AddUsersForm.getHeightFromWidth;
import config.PanelPrinter;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author CYBER SECURITY
 */
public class PrintingReciepts extends javax.swing.JFrame {

    /**
     * Creates new form individualPrinting
     */
    public PrintingReciepts() {
        initComponents();
    }
     public  ImageIcon ResizeImage(String ImagePath, byte[] pic, JLabel label) {
         ImageIcon MyImage = null;
             if(ImagePath !=null){
                 MyImage = new ImageIcon(ImagePath);
             }else{
                 MyImage = new ImageIcon(pic);
             }

         int newHeight = getHeightFromWidth(ImagePath, label.getWidth());

         Image img = MyImage.getImage();
         Image newImg = img.getScaledInstance(label.getWidth(), newHeight, Image.SCALE_SMOOTH);
         ImageIcon image = new ImageIcon(newImg);
         return image;
} 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header8 = new javax.swing.JPanel();
        header7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        page = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        lastname = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Status = new javax.swing.JLabel();
        adoption_id = new javax.swing.JLabel();
        a_id = new javax.swing.JLabel();
        p_id = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        print = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        header8.setBackground(new java.awt.Color(255, 255, 255));
        header8.setLayout(null);

        header7.setBackground(new java.awt.Color(80, 101, 91));
        header7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("INDIVIDUAL PRINTING");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        header7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 290, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("BACK");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        header7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 90, 50));

        header8.add(header7);
        header7.setBounds(0, 0, 560, 50);

        page.setBackground(new java.awt.Color(80, 101, 91));
        page.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ST. CECELIA'S COLLEGE  - CEBU, INC.");
        page.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 17, 440, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Patag, City of Naga, Cebu");
        page.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 45, 428, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        page.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 520, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel6.setText("Adoption ID:");
        page.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 102, 25));

        lastname.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        lastname.setText("Costumer Name :");
        page.add(lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 120, 25));

        jLabel8.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel8.setText("Pet Type:");
        page.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 102, 25));

        jLabel9.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel9.setText("Date:");
        page.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 102, 25));

        Status.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        Status.setText("Adoption Status:");
        page.add(Status, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 120, 25));

        adoption_id.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        adoption_id.setForeground(new java.awt.Color(255, 255, 255));
        page.add(adoption_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 170, 25));

        a_id.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        a_id.setForeground(new java.awt.Color(255, 255, 255));
        page.add(a_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 168, 25));

        p_id.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        p_id.setForeground(new java.awt.Color(255, 255, 255));
        page.add(p_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 168, 25));

        date.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        date.setForeground(new java.awt.Color(255, 255, 255));
        page.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 168, 25));

        status.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        status.setForeground(new java.awt.Color(255, 255, 255));
        page.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 168, 25));

        jLabel4.setText("from any liability for issues that may arise after the adoption.");
        page.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 480, 20));

        jLabel7.setText(" ☐ The applicant acknowledges that the pet is adopted \"as is,\" with no guarantees");
        page.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 450, 20));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        page.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 520, -1));

        jLabel10.setText("  regarding its behavior, health, or adaptability. The current owner makes no promises,");
        page.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 480, 20));

        jLabel11.setText(" expressed or implied, about the animal’s future conduct or compatibility. The applicant");
        page.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 480, 20));

        jLabel12.setText("accepts full responsibility for the pet’s care and well-being.The current owner is released");
        page.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 500, 20));

        header8.add(page);
        page.setBounds(20, 110, 520, 420);

        print.setBackground(new java.awt.Color(0, 204, 255));
        print.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        print.setText("PRINT");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        header8.add(print);
        print.setBounds(40, 60, 100, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(header8, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 557, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(header8, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked

        requestForm adf = new   requestForm  ();
        adf.setVisible(true);
        this.dispose(); 

    }//GEN-LAST:event_jLabel1MouseClicked

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
      
        JPanel myPanel =  new JPanel();
        PanelPrinter Pprint = new PanelPrinter(page);
        Pprint.printPanel();
        
    }//GEN-LAST:event_printActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrintingReciepts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrintingReciepts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrintingReciepts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrintingReciepts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrintingReciepts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Status;
    public javax.swing.JLabel a_id;
    public javax.swing.JLabel adoption_id;
    public javax.swing.JLabel date;
    private javax.swing.JPanel header7;
    private javax.swing.JPanel header8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lastname;
    public javax.swing.JLabel p_id;
    private javax.swing.JPanel page;
    public javax.swing.JButton print;
    public javax.swing.JLabel status;
    // End of variables declaration//GEN-END:variables
}
