/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import config.Session;
import config.dbConnect;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author CYBER SECURITY
 */
public class UsersForm extends javax.swing.JFrame {
     
    /**
     * Creates new form adminDashboard
     */ 
       

    public UsersForm() {
        initComponents();
         this.setLocationRelativeTo(null); // Make Jframe Center allighnment
        displayData();
       
        
    } 
    
      
                  
       Color nc=new Color( 0,0,153);
       Color hc=new Color(77,85,204);
       
        void displayData(){
        try{
            dbConnect dbc = new dbConnect();
            ResultSet rst = dbc.getData("SELECT * FROM accounts");
            usersTable.setModel(DbUtils.resultSetToTableModel(rst));
             rst.close();
        }catch(SQLException ex){
            System.out.println("Errors: "+ex.getMessage());

        }
        
        
        

    }
          
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        Uback = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        body = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        usersTable = new javax.swing.JTable();
        header6 = new javax.swing.JPanel();
        U_id = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        p_add = new javax.swing.JPanel();
        U_id1 = new javax.swing.JLabel();
        U_id2 = new javax.swing.JLabel();
        print = new javax.swing.JPanel();
        U_id4 = new javax.swing.JLabel();
        edit = new javax.swing.JPanel();
        U_id3 = new javax.swing.JLabel();
        header1 = new javax.swing.JPanel();

        header.setBackground(new java.awt.Color(204, 204, 204));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        Uback.setBackground(new java.awt.Color(5, 92, 147));
        Uback.setForeground(new java.awt.Color(5, 92, 157));
        Uback.setPreferredSize(new java.awt.Dimension(760, 60));
        Uback.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BACK");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        Uback.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 60, 60));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("USERS FORM");
        Uback.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 170, 60));

        getContentPane().add(Uback);
        Uback.setBounds(0, 0, 760, 60);

        body.setBackground(new java.awt.Color(0, 51, 102));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        body.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        usersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(usersTable);

        body.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 590, 400));

        header6.setBackground(new java.awt.Color(77, 85, 204));
        header6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        U_id.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        U_id.setForeground(new java.awt.Color(255, 255, 255));
        U_id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        U_id.setText("ID");
        U_id.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        U_id.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                U_idMouseClicked(evt);
            }
        });
        header6.add(U_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 130, 40));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user-removebg-preview (1).png"))); // NOI18N
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        header6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 100));

        p_add.setBackground(new java.awt.Color(77, 85, 204));
        p_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_addMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p_addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p_addMouseExited(evt);
            }
        });
        p_add.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        U_id1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        U_id1.setForeground(new java.awt.Color(255, 255, 255));
        U_id1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        U_id1.setText("ADD");
        U_id1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        U_id1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                U_id1MouseClicked(evt);
            }
        });
        p_add.add(U_id1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 80, 10));

        header6.add(p_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 130, 30));

        U_id2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        U_id2.setForeground(new java.awt.Color(255, 255, 255));
        U_id2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        U_id2.setText("Current User ID");
        U_id2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        U_id2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                U_id2MouseClicked(evt);
            }
        });
        header6.add(U_id2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 130, 40));

        print.setBackground(new java.awt.Color(77, 85, 204));
        print.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                printMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                printMouseExited(evt);
            }
        });
        print.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        U_id4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        U_id4.setForeground(new java.awt.Color(255, 255, 255));
        U_id4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        U_id4.setText("PRINT");
        U_id4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        U_id4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                U_id4MouseClicked(evt);
            }
        });
        print.add(U_id4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 50, 10));

        header6.add(print, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 130, 30));

        edit.setBackground(new java.awt.Color(77, 85, 204));
        edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editMouseExited(evt);
            }
        });
        edit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        U_id3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        U_id3.setForeground(new java.awt.Color(255, 255, 255));
        U_id3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        U_id3.setText("EDIT");
        U_id3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        U_id3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                U_id3MouseClicked(evt);
            }
        });
        edit.add(U_id3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 80, 10));

        header6.add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 130, 30));

        body.add(header6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 420));

        getContentPane().add(body);
        body.setBounds(0, 60, 760, 420);

        header1.setBackground(new java.awt.Color(204, 204, 204));
        header1.setLayout(null);
        getContentPane().add(header1);
        header1.setBounds(0, 0, 760, 50);

        setSize(new java.awt.Dimension(770, 520));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
           
      
        AdminDashboard adb = new AdminDashboard();
        adb.setVisible(true);
        this.dispose();
    
             
    }//GEN-LAST:event_jLabel1MouseClicked

    private void U_idMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_U_idMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_U_idMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
         Session ses = Session.getInstance(); 
        U_id.setText(""+ses.getA_id());
        
    }//GEN-LAST:event_formWindowActivated

    private void U_id1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_U_id1MouseClicked
        AddUsersForm af=new AddUsersForm();
                af.setVisible(true);
                this.dispose();
                
    }//GEN-LAST:event_U_id1MouseClicked

    private void p_addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_addMouseEntered
        
        
       
        
        p_add.setBackground(nc);
    }//GEN-LAST:event_p_addMouseEntered

    private void p_addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_addMouseExited
        p_add.setBackground(hc);
    }//GEN-LAST:event_p_addMouseExited

    private void U_id2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_U_id2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_U_id2MouseClicked

    private void p_addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_addMouseClicked
        
        AddUsersForm adf=new   AddUsersForm ();
        adf.setVisible(true);
        
        adf.remove.setEnabled(false);
        adf.select.setEnabled(true);
         this.dispose();
    }//GEN-LAST:event_p_addMouseClicked

    private void U_id3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_U_id3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_U_id3MouseClicked

    private void editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseClicked
        
          int rowIndex  = usersTable.getSelectedRow();
           if(rowIndex < 0){
               JOptionPane.showMessageDialog(null,"Please Select Item!");
           }else{
               
               try{
               dbConnect dbc = new dbConnect();
                 TableModel tbl= usersTable.getModel();
              ResultSet rs=dbc.getData("SELECT * FROM accounts WHERE a_id ='"+tbl.getValueAt(rowIndex, 0)+"'"); 
            if(rs.next()){  
                 AddUsersForm adf = new AddUsersForm();
              adf.u_id.setText(""+rs.getInt("a_id"));
              adf.fname.setText(""+rs.getString("firstname"));
              adf.lname.setText(""+rs.getString("lastname"));
              adf.em.setText(""+rs.getString("email"));
              adf.ustatus.setSelectedItem(""+rs.getString("status"));
              adf.utype.setSelectedItem(""+rs.getString("type"));
              adf.password.setText(""+rs.getString("password"));
              adf.uname.setText(""+rs.getString("username"));
              adf.nu.setText(""+rs.getString("contact"));
              adf.image.setIcon(adf.ResizeImage(rs.getString("u_image"), null, adf.image));
              adf.oldpath = rs.getString("u_image");
              adf.path = rs.getString("u_image");
              adf.destination = rs.getString("u_image");
               
               
              adf.u_add.setEnabled(false);
              adf.u_update.setEnabled(true);
              adf.setVisible(true);
              this.dispose();
              
               if(rs.getString("u_image").isEmpty()){
                   adf.select.setEnabled(true);
                     adf.remove.setEnabled(false);
               }else{
                 adf.select.setEnabled(false);
                     adf.remove.setEnabled(true);   
               }   
               }
               }catch(SQLException ex){
                   System.out.println("Connection Error!"+ex);
               }
           }
       
        
    }//GEN-LAST:event_editMouseClicked

    private void editMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseEntered
         edit.setBackground(nc);
    }//GEN-LAST:event_editMouseEntered

    private void editMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseExited
         edit.setBackground(hc);
    }//GEN-LAST:event_editMouseExited

    private void U_id4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_U_id4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_U_id4MouseClicked

    private void printMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printMouseClicked
        int rowIndex  = usersTable.getSelectedRow();
           if(rowIndex < 0){
               JOptionPane.showMessageDialog(null,"Please Select Item!");
           }else{
               
               try{
               dbConnect dbc = new dbConnect();
                 TableModel tbl= usersTable.getModel();
              ResultSet rs=dbc.getData("SELECT * FROM accounts WHERE a_id ='"+tbl.getValueAt(rowIndex, 0)+"'"); 
            if(rs.next()){  
                 individualPrinting ipt = new individualPrinting();
            ipt.id.setText(""+rs.getInt("a_id"));
            ipt.fname.setText(""+rs.getString("firstname"));
            ipt.lname.setText(""+rs.getString("lastname"));
             ipt.em.setText(""+rs.getString("email"));
              ipt.status.setText(""+rs.getString("status"));
              ipt.utype.setText(""+rs.getString("type")); 
              ipt.uname.setText(""+rs.getString("username"));
              
              
              ipt.image.setIcon(ipt.ResizeImage(rs.getString("u_image"), null, ipt.image));
              ipt.setVisible(true);
              this.dispose();
             
               }
               }catch(SQLException ex){
                   System.out.println("Connection Error!"+ex);
               }
           }
    }//GEN-LAST:event_printMouseClicked

    private void printMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printMouseEntered
        print.setBackground(nc);
    }//GEN-LAST:event_printMouseEntered

    private void printMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printMouseExited
         print.setBackground(nc);
    }//GEN-LAST:event_printMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsersForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel U_id;
    private javax.swing.JLabel U_id1;
    private javax.swing.JLabel U_id2;
    private javax.swing.JLabel U_id3;
    private javax.swing.JLabel U_id4;
    private javax.swing.JPanel Uback;
    private javax.swing.JPanel body;
    private javax.swing.JPanel edit;
    private javax.swing.JPanel header;
    private javax.swing.JPanel header1;
    private javax.swing.JPanel header6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel p_add;
    private javax.swing.JPanel print;
    private javax.swing.JTable usersTable;
    // End of variables declaration//GEN-END:variables
}
