/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

/**
 *
 * @author CYBER SECURITY
 */
public class usersTable extends javax.swing.JFrame {

    /**
     * Creates new form usersTable
     */
    public usersTable() {
        initComponents();
        
      
    }
   
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        navbar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        petadoption = new javax.swing.JLabel();
        header1 = new javax.swing.JPanel();
        CanUsers = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        users = new javax.swing.JButton();

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        body.add(jPanel3);
        jPanel3.setBounds(0, 0, 0, 0);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        navbar.setBackground(new java.awt.Color(0, 102, 102));
        navbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/petAdopt-removebg-preview.png"))); // NOI18N
        navbar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 370));

        petadoption.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        petadoption.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        petadoption.setText("PET ADOPTION");
        navbar.add(petadoption, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 480, -1));

        getContentPane().add(navbar);
        navbar.setBounds(170, 52, 480, 370);

        header1.setBackground(new java.awt.Color(204, 204, 204));
        header1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CanUsers.setBackground(new java.awt.Color(204, 204, 204));
        CanUsers.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CanUsers.setText("X");
        CanUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CanUsersActionPerformed(evt);
            }
        });
        header1.add(CanUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 12, -1, 30));

        getContentPane().add(header1);
        header1.setBounds(0, 0, 620, 50);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        users.setBackground(new java.awt.Color(0, 204, 255));
        users.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        users.setForeground(new java.awt.Color(255, 255, 255));
        users.setText("USERS");
        users.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usersActionPerformed(evt);
            }
        });
        jPanel1.add(users, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 140, 70));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 50, 170, 370);

        setSize(new java.awt.Dimension(636, 459));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usersActionPerformed
            
        
          adminDashboard adb = new adminDashboard();
                adb.setVisible(true);
                this.dispose();
                
        
    }//GEN-LAST:event_usersActionPerformed

    private void CanUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CanUsersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CanUsersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(usersTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(usersTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(usersTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(usersTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new usersTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CanUsers;
    private javax.swing.JPanel body;
    private javax.swing.JPanel header1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel navbar;
    private javax.swing.JLabel petadoption;
    private javax.swing.JButton users;
    // End of variables declaration//GEN-END:variables
}
