/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import config.Session;
import config.dbConnect;
import java.sql.ResultSet;
import java.sql.SQLException;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author CYBER SECURITY
 */
public class UsersForm extends javax.swing.JFrame {
     
    /**
     * Creates new form adminDashboard
     */ 
       

    public UsersForm() {
        initComponents();
         this.setLocationRelativeTo(null); // Make Jframe Center allighnment
        displayData();
       
        
    } 
                  
    
        void displayData(){
        try{
            dbConnect dbc = new dbConnect();
            ResultSet rst = dbc.getData("SELECT * FROM accounts");
            users.setModel(DbUtils.resultSetToTableModel(rst));
             rst.close();
        }catch(SQLException ex){
            System.out.println("Errors: "+ex.getMessage());

        }
        
        
        

    }
          
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        Uback = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        body = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        users = new javax.swing.JTable();
        header6 = new javax.swing.JPanel();
        U_id = new javax.swing.JLabel();
        edit = new javax.swing.JLabel();
        delete = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        add1 = new javax.swing.JLabel();
        U_id1 = new javax.swing.JLabel();
        header1 = new javax.swing.JPanel();

        header.setBackground(new java.awt.Color(204, 204, 204));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        Uback.setBackground(new java.awt.Color(5, 92, 147));
        Uback.setForeground(new java.awt.Color(5, 92, 157));
        Uback.setPreferredSize(new java.awt.Dimension(760, 60));
        Uback.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BACK");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        Uback.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 60, 60));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("USERS FORM");
        Uback.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 170, 60));

        getContentPane().add(Uback);
        Uback.setBounds(0, 0, 760, 60);

        body.setBackground(new java.awt.Color(0, 51, 102));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        body.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        users.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(users);

        body.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 590, 400));

        header6.setBackground(new java.awt.Color(0, 48, 98));
        header6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        U_id.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        U_id.setForeground(new java.awt.Color(255, 255, 255));
        U_id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        U_id.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        U_id.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                U_idMouseClicked(evt);
            }
        });
        header6.add(U_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 130, 40));

        edit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        edit.setForeground(new java.awt.Color(255, 255, 255));
        edit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        edit.setText("Edit");
        edit.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });
        header6.add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 130, 40));

        delete.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        delete.setText("Delete");
        delete.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });
        header6.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 130, 40));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user-removebg-preview (1).png"))); // NOI18N
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        header6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 100));

        add1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        add1.setForeground(new java.awt.Color(255, 255, 255));
        add1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add1.setText("Add");
        add1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        add1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add1MouseClicked(evt);
            }
        });
        header6.add(add1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 130, 40));

        U_id1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        U_id1.setForeground(new java.awt.Color(255, 255, 255));
        U_id1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        U_id1.setText("Current User ID");
        U_id1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        U_id1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                U_id1MouseClicked(evt);
            }
        });
        header6.add(U_id1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 130, 40));

        body.add(header6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 420));

        getContentPane().add(body);
        body.setBounds(0, 60, 760, 420);

        header1.setBackground(new java.awt.Color(204, 204, 204));
        header1.setLayout(null);
        getContentPane().add(header1);
        header1.setBounds(0, 0, 760, 50);

        setSize(new java.awt.Dimension(770, 520));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
           
      
        AdminDashboard adb = new AdminDashboard();
        adb.setVisible(true);
        this.dispose();
    
             
    }//GEN-LAST:event_jLabel1MouseClicked

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteMouseClicked

    private void U_idMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_U_idMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_U_idMouseClicked

    private void editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_editMouseClicked

    private void add1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_add1MouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
         Session ses = Session.getInstance(); 
        U_id.setText(""+ses.getA_id());
        
    }//GEN-LAST:event_formWindowActivated

    private void U_id1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_U_id1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_U_id1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsersForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel U_id;
    private javax.swing.JLabel U_id1;
    private javax.swing.JPanel Uback;
    private javax.swing.JLabel add1;
    private javax.swing.JPanel body;
    private javax.swing.JLabel delete;
    private javax.swing.JLabel edit;
    private javax.swing.JPanel header;
    private javax.swing.JPanel header1;
    private javax.swing.JPanel header6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable users;
    // End of variables declaration//GEN-END:variables
}
