
import config.dbConnect;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author CYBER SECURITY
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
          this.setLocationRelativeTo(null); // Make Jframe Center allighnment
    }
   public static  String email,usname;
      public boolean duplicateCheck(){
          dbConnect dbc =  new dbConnect();
          
          try{ String query = "SELECT * FROM accounts WHERE username ='"+uname.getText()+ "' OR  email = '"+em.getText()+"'";
                ResultSet resultSet = dbc.getData(query);
              
                 if (resultSet.next()){
                     email=resultSet.getString("email");
                        if(email.equals(em.getText())){
                            JOptionPane.showMessageDialog(null,"Email is already used!");
                            em.setText("");
                        }
                        usname=resultSet.getString("username");
                          if(usname.equals(uname.getText())){
                            JOptionPane.showMessageDialog(null,"Username is already used!");}
                             uname.setText("");
                     return true;
                 }else{
                     return false;
                 }
                
                }catch(SQLException ex){
                  System.out.println("" + ex);
                     return false;
                 }
      
      }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navbar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        petadoption = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        body = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        username = new javax.swing.JLabel();
        uname = new javax.swing.JTextField();
        username1 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        cancel = new javax.swing.JButton();
        login1 = new javax.swing.JButton();
        firstname = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        lastname = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        jpanelEmail = new javax.swing.JLabel();
        em = new javax.swing.JTextField();
        usertype = new javax.swing.JLabel();
        ULform1 = new javax.swing.JLabel();
        ut = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        navbar.setBackground(new java.awt.Color(0, 102, 102));
        navbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/petAdopt-removebg-preview.png"))); // NOI18N
        navbar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 380));

        petadoption.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        petadoption.setText("PET ADOPTION");
        navbar.add(petadoption, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 190, -1));

        header.setBackground(new java.awt.Color(204, 204, 204));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        body.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        username.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        username.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        username.setText("Password:");
        body.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 90, 20));

        uname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unameActionPerformed(evt);
            }
        });
        body.add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 180, -1));

        username1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        username1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        username1.setText("Username:");
        body.add(username1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        body.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 180, -1));

        cancel.setBackground(new java.awt.Color(255, 51, 51));
        cancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cancel.setForeground(new java.awt.Color(255, 255, 255));
        cancel.setText("Cancel");
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
        });
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        body.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 100, -1));

        login1.setBackground(new java.awt.Color(0, 204, 255));
        login1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        login1.setForeground(new java.awt.Color(255, 255, 255));
        login1.setText("Register");
        login1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login1ActionPerformed(evt);
            }
        });
        body.add(login1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 100, -1));

        firstname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        firstname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        firstname.setText("First Name:");
        body.add(firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });
        body.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 180, -1));

        lastname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lastname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lastname.setText("Last Name:");
        body.add(lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameActionPerformed(evt);
            }
        });
        body.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 180, -1));

        jpanelEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jpanelEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jpanelEmail.setText("Email:");
        body.add(jpanelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        em.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emActionPerformed(evt);
            }
        });
        body.add(em, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 180, -1));

        usertype.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        usertype.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usertype.setText("UserType:");
        body.add(usertype, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, 20));

        ULform1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ULform1.setText("REGISTRATION FORM");
        body.add(ULform1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        ut.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ut.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select UserType", "User", "Admin" }));
        body.add(ut, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 180, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(navbar, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(body, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(navbar, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(body, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void unameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unameActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
  
    }//GEN-LAST:event_cancelActionPerformed

    private void login1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login1ActionPerformed
      
            
         dbConnect dbc=new dbConnect(); 
         
           if  
               (fname.getText().isEmpty() || lname.getText().isEmpty() 
               || em.getText().isEmpty() 
                || ut.getSelectedIndex()==0
               || uname.getText().isEmpty() 
               || password.getText().isEmpty() ){
                JOptionPane.showMessageDialog(null,"All fields are required!"); //validation for register...  
                
               }else if (password.getText().length()< 8){
                          JOptionPane.showMessageDialog(null," Password should contain atleast 8 character above!"); 
                          password.setText("");
                        }
               else if(duplicateCheck()){
                         System.out.println("Duplicate Exist!");}
                   else if (dbc. insertData("INSERT INTO accounts(firstname, lastname, email, type, username, password, status) "
                    + "VALUES('"+fname.getText()+"',"
                    + "'"+lname.getText()+"',"
                    + "'"+em.getText()+"',"
                    + "'"+ut.getSelectedItem()+"',"
                    + "'"+uname.getText()+"',"
                    + "'"+ password.getText()+"','Pending')") ==1)
           {
                JOptionPane.showMessageDialog(null, "Succesfully Register");
                  Login lg = new Login();
                  lg.show();
                  this.dispose();
          
            } else {
                    JOptionPane.showMessageDialog(null,"Connection error!!");
                   }
             
    }//GEN-LAST:event_login1ActionPerformed

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed

    private void lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameActionPerformed

    private void emActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
  
   
    }//GEN-LAST:event_passwordActionPerformed

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
         Login lg = new Login();
                  lg.show();
                  this.dispose();
    }//GEN-LAST:event_cancelMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ULform1;
    private javax.swing.JPanel body;
    private javax.swing.JButton cancel;
    private javax.swing.JTextField em;
    private javax.swing.JLabel firstname;
    private javax.swing.JTextField fname;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jpanelEmail;
    private javax.swing.JLabel lastname;
    private javax.swing.JTextField lname;
    private javax.swing.JButton login1;
    private javax.swing.JPanel navbar;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel petadoption;
    private javax.swing.JTextField uname;
    private javax.swing.JLabel username;
    private javax.swing.JLabel username1;
    private javax.swing.JLabel usertype;
    private javax.swing.JComboBox<String> ut;
    // End of variables declaration//GEN-END:variables
}
