package LoginRegister;



import User.UsersDashboard;
import admin.AdminDashboard;
import config.Session;
import config.dbConnect;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author CYBER SECURITY
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null); // Make Jframe Center allighnment
    } 
     static String status; 
       static String atype; 
     
    public static boolean LoginAcc(String username, String password ){
        dbConnect  connect = new dbConnect();
        
        try{
        String query = "SELECT * FROM accounts WHERE username ='"+username+ "' AND password = '"+password+"'";
            ResultSet resultSet = connect.getData(query);
            if(resultSet.next()){
                status = resultSet.getString("status");
                atype = resultSet.getString("type");
                   
                    Session ses = Session.getInstance();
                    ses.setA_id(resultSet.getInt("a_id") );
                    ses.setFirstame(resultSet.getString("firstname") );
                    ses.setLastnmae(resultSet.getString("lastname") );
                    ses.setEmail(resultSet.getString("email") );
                    ses.setType(resultSet.getString("type") );
                    ses.setUsername(resultSet.getString("username") );
                    ses.setStatus(resultSet.getString("username") );
              
                 return true;}
                 else{
                 return false;}
             
                
        }catch(SQLException ex){
            return false ;
    }
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        ULform1 = new javax.swing.JLabel();
        username1 = new javax.swing.JLabel();
        uname = new javax.swing.JTextField();
        ps = new javax.swing.JPasswordField();
        username = new javax.swing.JLabel();
        jLabel2Registration = new javax.swing.JLabel();
        Unavbar = new javax.swing.JPanel();
        uback = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ULform1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        ULform1.setForeground(new java.awt.Color(255, 204, 51));
        ULform1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ULform1.setText("USER LOGIN FORM");
        ULform1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(ULform1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 370, 100));

        username1.setBackground(new java.awt.Color(204, 204, 204));
        username1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        username1.setForeground(new java.awt.Color(204, 204, 204));
        username1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        username1.setText("Username:");
        getContentPane().add(username1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, -1, -1));

        uname.setBackground(new java.awt.Color(204, 204, 204));
        uname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unameActionPerformed(evt);
            }
        });
        getContentPane().add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 250, 30));

        ps.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(ps, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 250, 30));

        username.setBackground(new java.awt.Color(204, 204, 204));
        username.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        username.setForeground(new java.awt.Color(204, 204, 204));
        username.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        username.setText("Password:");
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 80, -1));

        jLabel2Registration.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2Registration.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2Registration.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2Registration.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2Registration.setText("Click here to create a new Account...");
        jLabel2Registration.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2Registration.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2RegistrationMouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2Registration, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 360, -1));

        Unavbar.setBackground(new java.awt.Color(0,0,0,60));
        Unavbar.setForeground(new java.awt.Color(153, 153, 153));
        Unavbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        uback.setBackground(new java.awt.Color(255, 11, 51));
        uback.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        uback.setForeground(new java.awt.Color(255, 255, 255));
        uback.setText("BACK");
        uback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubackActionPerformed(evt);
            }
        });
        Unavbar.add(uback, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 70, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        Unavbar.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 30));

        getContentPane().add(Unavbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 380, 400));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 760, 20));

        login.setBackground(new java.awt.Color(0, 204, 255));
        login.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 320, 90, 30));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Gbackground (1).png"))); // NOI18N
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 480));

        setSize(new java.awt.Dimension(774, 520));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void unameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unameActionPerformed

    private void jLabel2RegistrationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2RegistrationMouseClicked

        Register rg = new Register();
        rg.show(); // to display ang register dre dapita nga code....
        dispose(); //ma close ang current jframe or log in...
    }//GEN-LAST:event_jLabel2RegistrationMouseClicked

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed

        if (LoginAcc(uname.getText(),ps.getText() ) ){
            if (!status.equals("Active")){
                JOptionPane.showMessageDialog(null,"Only active User can login");

            }else{

                if (atype.equals("Admin")){
                    JOptionPane.showMessageDialog(null, "Login Succesfully!");
                    AdminDashboard ut = new AdminDashboard();
                    ut.setVisible(true);
                    this.dispose();
                }else if (atype.equals("User")){
                    JOptionPane.showMessageDialog(null, "Login Succesfully!");
                    UsersDashboard adb = new UsersDashboard();
                    adb.setVisible(true);
                    this.dispose();
                }else {
                    JOptionPane.showMessageDialog(null,"No account type found, Contact the Admin");
                }

            }
        }else if (uname.getText().isEmpty() || ps.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null,"please fill out all fields!"); //validation for login...

        }  else {
            JOptionPane.showMessageDialog(null," Login Failed!");
        }
    }//GEN-LAST:event_loginActionPerformed

    private void ubackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubackActionPerformed
        AdminDashboard ut = new AdminDashboard();
        ut.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_ubackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ULform1;
    private javax.swing.JPanel Unavbar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel2Registration;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JButton login;
    private javax.swing.JPasswordField ps;
    private javax.swing.JButton uback;
    private javax.swing.JTextField uname;
    private javax.swing.JLabel username;
    private javax.swing.JLabel username1;
    // End of variables declaration//GEN-END:variables
}
