package LoginRegister;



import ForgotPassword.forgotPassword;
import User.UsersDashboard;
import admin.AdminDashboard;
import config.Session;
import config.dbConnect;
import config.passwordHasher;
import java.awt.Color;
import java.security.NoSuchAlgorithmException;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author CYBER SECURITY
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null); 
    } 
      Color sp=new Color(0,204,255);
       Color nc=new Color(0,153,204);
       Color hc=new Color(0,102,102);
     static String status; 
       static String atype; 
     
    public static boolean LoginAcc(String username, String pass){
        dbConnect  connect = new dbConnect();
        
        try{
        String query = "SELECT * FROM accounts WHERE username ='"+username+ "' ";
            ResultSet resultSet = connect.getData(query);
            if(resultSet.next()){
                
             
                String hashedPass= resultSet.getString("password");
                String rehashedPass = passwordHasher.hashPassword(pass);
                
                  
                     
                  if ( hashedPass.equals(rehashedPass )){
                       status = resultSet.getString("status");
                        atype = resultSet.getString("type");
                   
                    Session ses = Session.getInstance();
                    ses.setA_id(resultSet.getInt("a_id") );
                    ses.setFirstame(resultSet.getString("firstname") );
                    ses.setLastnmae(resultSet.getString("lastname") );
                    ses.setEmail(resultSet.getString("email") );
                    ses.setType(resultSet.getString("type") );
                    ses.setUsername(resultSet.getString("username") );
                    ses.setStatus(resultSet.getString("status") );
              
                 return true;
                  }else{
                  return false;
                  }
                  
                } else{
                 return false;
            }
            
        }catch(SQLException | NoSuchAlgorithmException ex){
            return false ;
        }
    }   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        hv = new javax.swing.JPanel();
        ULform1 = new javax.swing.JLabel();
        username1 = new javax.swing.JLabel();
        uname = new javax.swing.JTextField();
        username = new javax.swing.JLabel();
        ps = new javax.swing.JPasswordField();
        users = new javax.swing.JLabel();
        showpass = new javax.swing.JCheckBox();
        jLabel2Registration = new javax.swing.JLabel();
        sigin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nv = new javax.swing.JPanel();
        jLabel2Registration1 = new javax.swing.JLabel();
        sip = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2Registration2 = new javax.swing.JLabel();
        jLabel2Registration3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().setLayout(null);

        hv.setBackground(new java.awt.Color(255, 255, 255));
        hv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hvMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hvMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hvMouseExited(evt);
            }
        });
        hv.setLayout(null);

        ULform1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        ULform1.setForeground(new java.awt.Color(0, 204, 204));
        ULform1.setText("LOGIN ");
        ULform1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        hv.add(ULform1);
        ULform1.setBounds(10, 0, 170, 70);

        username1.setBackground(new java.awt.Color(204, 204, 204));
        username1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        username1.setText("Enter Username:");
        hv.add(username1);
        username1.setBounds(90, 100, 150, 20);

        uname.setBackground(new java.awt.Color(204, 204, 204));
        uname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unameActionPerformed(evt);
            }
        });
        hv.add(uname);
        uname.setBounds(90, 130, 250, 30);

        username.setBackground(new java.awt.Color(204, 204, 204));
        username.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        username.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        username.setText("Enter Password:");
        hv.add(username);
        username.setBounds(80, 190, 130, 17);

        ps.setBackground(new java.awt.Color(204, 204, 204));
        ps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psActionPerformed(evt);
            }
        });
        hv.add(ps);
        ps.setBounds(90, 210, 250, 30);

        users.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        users.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        users.setText("Forgot Password");
        users.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usersMouseClicked(evt);
            }
        });
        hv.add(users);
        users.setBounds(230, 260, 100, 30);

        showpass.setBackground(new java.awt.Color(0,0,0,60));
        showpass.setText("Show Password");
        showpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpassActionPerformed(evt);
            }
        });
        hv.add(showpass);
        showpass.setBounds(90, 260, 115, 20);

        jLabel2Registration.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2Registration.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2Registration.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2Registration.setText("Or Login in with");
        jLabel2Registration.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2Registration.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2RegistrationMouseClicked(evt);
            }
        });
        hv.add(jLabel2Registration);
        jLabel2Registration.setBounds(10, 400, 150, 30);

        sigin.setBackground(new java.awt.Color(0, 204, 255));
        sigin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sigin.setText("Sign in");
        sigin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                siginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                siginMouseExited(evt);
            }
        });
        sigin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siginActionPerformed(evt);
            }
        });
        hv.add(sigin);
        sigin.setBounds(160, 300, 100, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/faceboo__1_-removebg-preview (1).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        hv.add(jLabel1);
        jLabel1.setBounds(220, 400, 40, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/twitter (1).png"))); // NOI18N
        hv.add(jLabel2);
        jLabel2.setBounds(350, 400, 30, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/email (1).png"))); // NOI18N
        hv.add(jLabel3);
        jLabel3.setBounds(290, 400, 30, 30);

        getContentPane().add(hv);
        hv.setBounds(270, 0, 440, 460);

        nv.setBackground(new java.awt.Color(0, 102, 102));
        nv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nvMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nvMouseExited(evt);
            }
        });
        nv.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2Registration1.setBackground(new java.awt.Color(0, 204, 204));
        jLabel2Registration1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2Registration1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2Registration1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2Registration1.setText("PET ADOPTION");
        jLabel2Registration1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2Registration1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2Registration1MouseClicked(evt);
            }
        });
        nv.add(jLabel2Registration1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 250, 80));

        sip.setBackground(new java.awt.Color(0, 204, 255));
        sip.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sip.setText("Sign up");
        sip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sipMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sipMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sipMouseExited(evt);
            }
        });
        sip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sipActionPerformed(evt);
            }
        });
        nv.add(sip, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 90, 40));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LoginImage/logo pet (1) (2).png"))); // NOI18N
        nv.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 240, 230));

        jLabel2Registration2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2Registration2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2Registration2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2Registration2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2Registration2.setText("Hello Welcome Back,");
        jLabel2Registration2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2Registration2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2Registration2MouseClicked(evt);
            }
        });
        nv.add(jLabel2Registration2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 260, 210, 30));

        jLabel2Registration3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2Registration3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2Registration3.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2Registration3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2Registration3.setText("Choose your Pet here!");
        jLabel2Registration3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2Registration3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2Registration3MouseClicked(evt);
            }
        });
        nv.add(jLabel2Registration3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 230, 30));

        getContentPane().add(nv);
        nv.setBounds(0, 0, 270, 460);

        setSize(new java.awt.Dimension(722, 492));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2Registration1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2Registration1MouseClicked
         
    }//GEN-LAST:event_jLabel2Registration1MouseClicked

    private void hvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hvMouseClicked

     

    }//GEN-LAST:event_hvMouseClicked

    private void hvMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hvMouseEntered

        
    }//GEN-LAST:event_hvMouseEntered

    private void hvMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hvMouseExited
        
    }//GEN-LAST:event_hvMouseExited

    private void nvMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nvMouseEntered
        nv.setBackground(nc);

        // TODO add your handling code here:
    }//GEN-LAST:event_nvMouseEntered

    private void nvMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nvMouseExited
      nv.setBackground(hc);
    }//GEN-LAST:event_nvMouseExited

    private void sipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sipActionPerformed

    private void sipMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sipMouseClicked
        
       Register rg = new Register();
       rg.setVisible(true);
       this.dispose();
        
    }//GEN-LAST:event_sipMouseClicked

    private void jLabel2RegistrationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2RegistrationMouseClicked

    }//GEN-LAST:event_jLabel2RegistrationMouseClicked

    private void psActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_psActionPerformed

    private void usersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersMouseClicked
        forgotPassword fp=new forgotPassword ();
        fp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_usersMouseClicked

    private void siginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siginActionPerformed

        if (LoginAcc(uname.getText(),ps.getText() ) ){
            if (!status.equals("Active")){
                JOptionPane.showMessageDialog(null,"Only active User can login");

            }else{

                if (atype.equals("Admin")){
                    JOptionPane.showMessageDialog(null, "Login Succesfully!");
                    AdminDashboard ut = new AdminDashboard();
                    ut.setVisible(true);
                    this.dispose();
                }else if (atype.equals("User")){
                    JOptionPane.showMessageDialog(null, "Login Succesfully!");
                    UsersDashboard adb = new UsersDashboard();
                    adb.setVisible(true);
                    this.dispose();
                }else {
                    JOptionPane.showMessageDialog(null,"No account type found, Contact the Admin");
                }

            }
        }else if (uname.getText().isEmpty() || ps.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null,"please fill out all fields!"); //validation for login...

        }  else {
            JOptionPane.showMessageDialog(null,"Invalid Account!");
        }
    }//GEN-LAST:event_siginActionPerformed

    private void showpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpassActionPerformed

        if (showpass.isSelected()){
            ps.setEchoChar((char)0);
        }else{
            ps.setEchoChar('*');
        }

    }//GEN-LAST:event_showpassActionPerformed

    private void unameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unameActionPerformed

    private void sipMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sipMouseEntered
         
       sip.setBackground(nc);
      
    }//GEN-LAST:event_sipMouseEntered

    private void sipMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sipMouseExited
        sip.setBackground(hc);
         
    }//GEN-LAST:event_sipMouseExited

    private void jLabel2Registration2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2Registration2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2Registration2MouseClicked

    private void jLabel2Registration3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2Registration3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2Registration3MouseClicked

    private void siginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_siginMouseEntered

           sigin.setBackground(nc);
        // TODO add your handling code here:
    }//GEN-LAST:event_siginMouseEntered

    private void siginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_siginMouseExited
           sigin.setBackground(hc);
    }//GEN-LAST:event_siginMouseExited
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ULform1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel hv;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel2Registration;
    private javax.swing.JLabel jLabel2Registration1;
    private javax.swing.JLabel jLabel2Registration2;
    private javax.swing.JLabel jLabel2Registration3;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel nv;
    private javax.swing.JPasswordField ps;
    private javax.swing.JCheckBox showpass;
    private javax.swing.JButton sigin;
    private javax.swing.JButton sip;
    private javax.swing.JTextField uname;
    private javax.swing.JLabel username;
    private javax.swing.JLabel username1;
    private javax.swing.JLabel users;
    // End of variables declaration//GEN-END:variables
}
