package LoginRegister;




import config.dbConnect;
import config.passwordHasher;
import java.awt.Color;
import java.security.NoSuchAlgorithmException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author CYBER SECURITY
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
          this.setLocationRelativeTo(null); 
    }
    Color hc=new Color(0,153,204);
       Color nc=new Color(0,102,102);
   public static  String email,usname;
   
      public boolean duplicateCheck(){
          dbConnect dbc =  new dbConnect();try{ String query = "SELECT * FROM accounts WHERE username ='"+uname.getText()+ "' OR  email = '"+em.getText()+"'";
                ResultSet resultSet = dbc.getData(query);
              
                 if (resultSet.next()){
                     email=resultSet.getString("email");
                        if(email.equals(em.getText())){
                             JOptionPane.showMessageDialog(null,"Email is already used!");
                             em.setText("");  
                             return true;}
                             usname=resultSet.getString("username");
                          if(usname.equals(uname.getText())){
                             JOptionPane.showMessageDialog(null,"Username is already used!");}
                             uname.setText("");
                           return true;}
                 else{
                         return false;}
                
                }catch(SQLException ex){
                  System.out.println("" + ex);
                     return false;
                 }
      
      }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nv = new javax.swing.JPanel();
        jLabel2Registration1 = new javax.swing.JLabel();
        sip = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2Registration2 = new javax.swing.JLabel();
        Unavbar = new javax.swing.JPanel();
        em = new javax.swing.JTextField();
        showpass = new javax.swing.JCheckBox();
        password = new javax.swing.JPasswordField();
        Register = new javax.swing.JButton();
        username = new javax.swing.JLabel();
        nu = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jpanelEmail = new javax.swing.JLabel();
        ut = new javax.swing.JComboBox<>();
        usertype = new javax.swing.JLabel();
        uname = new javax.swing.JTextField();
        username1 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        firstname = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        lastname = new javax.swing.JLabel();
        ULform1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nv.setBackground(new java.awt.Color(0, 153, 204));
        nv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nvMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nvMouseExited(evt);
            }
        });
        nv.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2Registration1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2Registration1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2Registration1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2Registration1.setText("Create your account here!");
        jLabel2Registration1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2Registration1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2Registration1MouseClicked(evt);
            }
        });
        nv.add(jLabel2Registration1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 250, 70));

        sip.setBackground(new java.awt.Color(0, 255, 255));
        sip.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sip.setForeground(new java.awt.Color(255, 255, 255));
        sip.setText("Sign in");
        sip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sipMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sipMouseExited(evt);
            }
        });
        sip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sipActionPerformed(evt);
            }
        });
        nv.add(sip, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 100, 40));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LoginImage/logo pet (1) (2).png"))); // NOI18N
        nv.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 240, 230));

        jLabel2Registration2.setBackground(new java.awt.Color(0, 204, 204));
        jLabel2Registration2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2Registration2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2Registration2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2Registration2.setText("PET ADOPTION");
        jLabel2Registration2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2Registration2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2Registration2MouseClicked(evt);
            }
        });
        nv.add(jLabel2Registration2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 60));

        getContentPane().add(nv, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 290, 440));

        Unavbar.setBackground(new java.awt.Color(255, 255, 255));
        Unavbar.setForeground(new java.awt.Color(102, 102, 102));
        Unavbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        em.setBackground(new java.awt.Color(204, 204, 204));
        Unavbar.add(em, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 170, 30));

        showpass.setText("Show Password");
        showpass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showpassMouseClicked(evt);
            }
        });
        Unavbar.add(showpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 120, 30));

        password.setBackground(new java.awt.Color(204, 204, 204));
        Unavbar.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 150, 30));

        Register.setBackground(new java.awt.Color(0, 204, 255));
        Register.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Register.setForeground(new java.awt.Color(255, 255, 255));
        Register.setText("Register");
        Register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegisterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegisterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegisterMouseExited(evt);
            }
        });
        Unavbar.add(Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 100, 40));

        username.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        username.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        username.setText("Password:");
        Unavbar.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 100, 20));

        nu.setBackground(new java.awt.Color(204, 204, 204));
        nu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuActionPerformed(evt);
            }
        });
        Unavbar.add(nu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 150, 30));

        jLabel23.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel23.setText("Contact #:");
        Unavbar.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, 20));

        jpanelEmail.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jpanelEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jpanelEmail.setText("Email:");
        Unavbar.add(jpanelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 50, -1));

        ut.setBackground(new java.awt.Color(204, 204, 204));
        ut.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ut.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select UserType", "User", "Admin" }));
        Unavbar.add(ut, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 170, 30));

        usertype.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        usertype.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usertype.setText("User Type:");
        Unavbar.add(usertype, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 80, 20));

        uname.setBackground(new java.awt.Color(204, 204, 204));
        Unavbar.add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 150, 30));

        username1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        username1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        username1.setText("User Name:");
        Unavbar.add(username1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        fname.setBackground(new java.awt.Color(204, 204, 204));
        Unavbar.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 150, 30));

        firstname.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        firstname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        firstname.setText("First Name:");
        Unavbar.add(firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 90, -1));

        lname.setBackground(new java.awt.Color(204, 204, 204));
        Unavbar.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 170, 30));

        lastname.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lastname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lastname.setText("Last Name:");
        Unavbar.add(lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 90, -1));

        ULform1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        ULform1.setForeground(new java.awt.Color(0, 153, 204));
        ULform1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        ULform1.setText("REGISTER");
        ULform1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Unavbar.add(ULform1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 130, 60));

        getContentPane().add(Unavbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
        Login lg = new Login();
        lg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelMouseClicked

    private void sipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sipActionPerformed
        Login lg = new Login();
        lg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_sipActionPerformed

    private void login1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login1ActionPerformed

        

       

    }//GEN-LAST:event_login1ActionPerformed
    
    private void lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameActionPerformed

    private void emActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emActionPerformed

    }//GEN-LAST:event_emActionPerformed

    private void unameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unameActionPerformed

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void showpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpassActionPerformed

      

    }//GEN-LAST:event_showpassActionPerformed

    private void jLabel2Registration1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2Registration1MouseClicked

    }//GEN-LAST:event_jLabel2Registration1MouseClicked

    private void nvMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nvMouseEntered
        nv.setBackground(nc);

        // TODO add your handling code here:
    }//GEN-LAST:event_nvMouseEntered

    private void nvMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nvMouseExited
        nv.setBackground(hc);
    }//GEN-LAST:event_nvMouseExited

    private void nuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuActionPerformed

    private void RegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterMouseClicked
         if

        (fname.getText().isEmpty() || lname.getText().isEmpty()
            || em.getText().isEmpty()
            || ut.getSelectedIndex()==0
            || uname.getText().isEmpty()
            ||nu.getText().isEmpty()
            || password.getText().isEmpty() ){
            JOptionPane.showMessageDialog(null,"All fields are required!"); //validation for register...

            return ;

        }else if (password.getText().length()< 8){
            JOptionPane.showMessageDialog(null," Password should contain atleast 8 character above!");
            password.setText("");
            return;}

        String email = em.getText();
        String emailRegex = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$";
        Pattern patternEmail = Pattern.compile(emailRegex);
        Matcher matcherEmail = patternEmail.matcher(email);

        if (!matcherEmail.matches()) {
            JOptionPane.showMessageDialog(this, "Invalid email format. Please use a valid email address.", "Error", JOptionPane.ERROR_MESSAGE);
            em.setText("");
            em.requestFocus();

        }

        else if(duplicateCheck()){
            System.out.println("Duplicate Exist!");
      
        }
        else {
              dbConnect dbc=new dbConnect();
            
            try {
            String pass=passwordHasher.hashPassword(password.getText());
        
        if (dbc.insertData("INSERT INTO accounts(firstname, lastname, email, type, username, password, contact, status) "
        + "VALUES('"+fname.getText()+"',"
        + "'"+lname.getText()+"',"
        + "'"+em.getText()+"',"
        + "'"+ut.getSelectedItem()+"',"
        + "'"+uname.getText()+"',"
        + "'"+ pass+"'," 
        + "'"+nu.getText()+"','Pending')") == 1)
{
        JOptionPane.showMessageDialog(null, "Succesfully Register");
        Login lg = new Login();
        lg.show();
        this.dispose();

        } else {
            JOptionPane.showMessageDialog(null,"Connection error!!");
        }
    }catch(NoSuchAlgorithmException ex){
                System.out.println(""+ex);
                }
    }  
        
        
    }//GEN-LAST:event_RegisterMouseClicked

    private void showpassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showpassMouseClicked
   if (showpass.isSelected()){
            password.setEchoChar((char)0);
        }else{
            password.setEchoChar('*');
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_showpassMouseClicked

    private void jLabel2Registration2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2Registration2MouseClicked

    }//GEN-LAST:event_jLabel2Registration2MouseClicked

    private void sipMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sipMouseEntered
 
      sip.setBackground(hc);
        
    }//GEN-LAST:event_sipMouseEntered

    private void sipMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sipMouseExited


         sip.setBackground(nc);
    }//GEN-LAST:event_sipMouseExited

    private void RegisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterMouseEntered
         Register.setBackground(nc);
    }//GEN-LAST:event_RegisterMouseEntered

    private void RegisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterMouseExited
        Register.setBackground(hc);
    }//GEN-LAST:event_RegisterMouseExited
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Register;
    private javax.swing.JLabel ULform1;
    private javax.swing.JPanel Unavbar;
    private javax.swing.JTextField em;
    private javax.swing.JLabel firstname;
    private javax.swing.JTextField fname;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel2Registration1;
    private javax.swing.JLabel jLabel2Registration2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jpanelEmail;
    private javax.swing.JLabel lastname;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField nu;
    private javax.swing.JPanel nv;
    private javax.swing.JPasswordField password;
    private javax.swing.JCheckBox showpass;
    private javax.swing.JButton sip;
    private javax.swing.JTextField uname;
    private javax.swing.JLabel username;
    private javax.swing.JLabel username1;
    private javax.swing.JLabel usertype;
    private javax.swing.JComboBox<String> ut;
    // End of variables declaration//GEN-END:variables
}
