package LoginRegister;


import config.dbConnect;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author CYBER SECURITY
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
          this.setLocationRelativeTo(null); 
    }
    
   public static  String email,usname;
   
      public boolean duplicateCheck(){
          dbConnect dbc =  new dbConnect();try{ String query = "SELECT * FROM accounts WHERE username ='"+uname.getText()+ "' OR  email = '"+em.getText()+"'";
                ResultSet resultSet = dbc.getData(query);
              
                 if (resultSet.next()){
                     email=resultSet.getString("email");
                        if(email.equals(em.getText())){
                             JOptionPane.showMessageDialog(null,"Email is already used!");
                             em.setText("");  
                             return true;}
                             usname=resultSet.getString("username");
                          if(usname.equals(uname.getText())){
                             JOptionPane.showMessageDialog(null,"Username is already used!");}
                             uname.setText("");
                           return true;}
                 else{
                         return false;}
                
                }catch(SQLException ex){
                  System.out.println("" + ex);
                     return false;
                 }
      
      }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Unavbar = new javax.swing.JPanel();
        cancel = new javax.swing.JButton();
        lastname = new javax.swing.JLabel();
        login1 = new javax.swing.JButton();
        lname = new javax.swing.JTextField();
        jpanelEmail = new javax.swing.JLabel();
        em = new javax.swing.JTextField();
        username1 = new javax.swing.JLabel();
        uname = new javax.swing.JTextField();
        username = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        usertype = new javax.swing.JLabel();
        firstname = new javax.swing.JLabel();
        ut = new javax.swing.JComboBox<>();
        fname = new javax.swing.JTextField();
        ULform1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(760, 480));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Unavbar.setBackground(new java.awt.Color(0,0,0,60));
        Unavbar.setForeground(new java.awt.Color(102, 102, 102));
        Unavbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cancel.setBackground(new java.awt.Color(255, 51, 51));
        cancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cancel.setForeground(new java.awt.Color(255, 255, 255));
        cancel.setText("Cancel");
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
        });
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        Unavbar.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 100, -1));

        lastname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lastname.setForeground(new java.awt.Color(255, 255, 255));
        lastname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lastname.setText("Last Name:");
        Unavbar.add(lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        login1.setBackground(new java.awt.Color(0, 204, 255));
        login1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        login1.setForeground(new java.awt.Color(255, 255, 255));
        login1.setText("Register");
        login1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login1ActionPerformed(evt);
            }
        });
        Unavbar.add(login1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 100, -1));

        lname.setBackground(new java.awt.Color(204, 204, 204));
        lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameActionPerformed(evt);
            }
        });
        Unavbar.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 230, -1));

        jpanelEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jpanelEmail.setForeground(new java.awt.Color(255, 255, 255));
        jpanelEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jpanelEmail.setText("Email:");
        Unavbar.add(jpanelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        em.setBackground(new java.awt.Color(204, 204, 204));
        em.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emActionPerformed(evt);
            }
        });
        Unavbar.add(em, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 280, -1));

        username1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        username1.setForeground(new java.awt.Color(255, 255, 255));
        username1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        username1.setText("Username:");
        Unavbar.add(username1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        uname.setBackground(new java.awt.Color(204, 204, 204));
        uname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unameActionPerformed(evt);
            }
        });
        Unavbar.add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 211, -1));

        username.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        username.setText("Password:");
        Unavbar.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 90, 20));

        password.setBackground(new java.awt.Color(204, 204, 204));
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        Unavbar.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 280, -1));

        usertype.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        usertype.setForeground(new java.awt.Color(255, 255, 255));
        usertype.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usertype.setText("UserType:");
        Unavbar.add(usertype, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, 20));

        firstname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        firstname.setForeground(new java.awt.Color(255, 255, 255));
        firstname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        firstname.setText("First Name:");
        Unavbar.add(firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        ut.setBackground(new java.awt.Color(204, 204, 204));
        ut.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ut.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select UserType", "User", "Admin" }));
        Unavbar.add(ut, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 230, -1));

        fname.setBackground(new java.awt.Color(204, 204, 204));
        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });
        Unavbar.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 211, -1));

        getContentPane().add(Unavbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 540, 380));

        ULform1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        ULform1.setForeground(new java.awt.Color(255, 204, 51));
        ULform1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ULform1.setText("REGISTRATION FORM");
        ULform1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(ULform1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 60));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/GuiPetBackground.png"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
        Login lg = new Login();
        lg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelMouseClicked

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed

    }//GEN-LAST:event_cancelActionPerformed

    private void login1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login1ActionPerformed

        dbConnect dbc=new dbConnect();

        if

        (fname.getText().isEmpty() || lname.getText().isEmpty()
            || em.getText().isEmpty()
            || ut.getSelectedIndex()==0
            || uname.getText().isEmpty()
            || password.getText().isEmpty() ){
            JOptionPane.showMessageDialog(null,"All fields are required!"); //validation for register...

            return ;

        }else if (password.getText().length()< 8){
            JOptionPane.showMessageDialog(null," Password should contain atleast 8 character above!");
            password.setText("");
            return;}

        String email = em.getText();
        String emailRegex = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$";
        Pattern patternEmail = Pattern.compile(emailRegex);
        Matcher matcherEmail = patternEmail.matcher(email);

        if (!matcherEmail.matches()) {
            JOptionPane.showMessageDialog(this, "Invalid email format. Please use a valid email address.", "Error", JOptionPane.ERROR_MESSAGE);
            em.setText("");
            em.requestFocus();

        }

        else if(duplicateCheck()){
            System.out.println("Duplicate Exist!");

        }
        else if (dbc. insertData("INSERT INTO accounts(firstname, lastname, email, type, username, password, status) "
            + "VALUES('"+fname.getText()+"',"
            + "'"+lname.getText()+"',"
            + "'"+em.getText()+"',"
            + "'"+ut.getSelectedItem()+"',"
            + "'"+uname.getText()+"',"
            + "'"+ password.getText()+"','Pending')") ==1)

    {
        JOptionPane.showMessageDialog(null, "Succesfully Register");
        Login lg = new Login();
        lg.show();
        this.dispose();

        } else {
            JOptionPane.showMessageDialog(null,"Connection error!!");
        }
    }//GEN-LAST:event_login1ActionPerformed

    private void lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameActionPerformed

    private void emActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emActionPerformed

    }//GEN-LAST:event_emActionPerformed

    private void unameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unameActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed

    }//GEN-LAST:event_passwordActionPerformed

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ULform1;
    private javax.swing.JPanel Unavbar;
    private javax.swing.JButton cancel;
    private javax.swing.JTextField em;
    private javax.swing.JLabel firstname;
    private javax.swing.JTextField fname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jpanelEmail;
    private javax.swing.JLabel lastname;
    private javax.swing.JTextField lname;
    private javax.swing.JButton login1;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField uname;
    private javax.swing.JLabel username;
    private javax.swing.JLabel username1;
    private javax.swing.JLabel usertype;
    private javax.swing.JComboBox<String> ut;
    // End of variables declaration//GEN-END:variables
}
