package LoginRegister;


import config.dbConnect;
import config.passwordHasher;
import java.security.NoSuchAlgorithmException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author CYBER SECURITY
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
          this.setLocationRelativeTo(null); 
    }
    
   public static  String email,usname;
   
      public boolean duplicateCheck(){
          dbConnect dbc =  new dbConnect();try{ String query = "SELECT * FROM accounts WHERE username ='"+uname.getText()+ "' OR  email = '"+em.getText()+"'";
                ResultSet resultSet = dbc.getData(query);
              
                 if (resultSet.next()){
                     email=resultSet.getString("email");
                        if(email.equals(em.getText())){
                             JOptionPane.showMessageDialog(null,"Email is already used!");
                             em.setText("");  
                             return true;}
                             usname=resultSet.getString("username");
                          if(usname.equals(uname.getText())){
                             JOptionPane.showMessageDialog(null,"Username is already used!");}
                             uname.setText("");
                           return true;}
                 else{
                         return false;}
                
                }catch(SQLException ex){
                  System.out.println("" + ex);
                     return false;
                 }
      
      }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Unavbar = new javax.swing.JPanel();
        cancel = new javax.swing.JButton();
        lastname = new javax.swing.JLabel();
        login1 = new javax.swing.JButton();
        lname = new javax.swing.JTextField();
        jpanelEmail = new javax.swing.JLabel();
        em = new javax.swing.JTextField();
        username1 = new javax.swing.JLabel();
        uname = new javax.swing.JTextField();
        username = new javax.swing.JLabel();
        usertype = new javax.swing.JLabel();
        firstname = new javax.swing.JLabel();
        ut = new javax.swing.JComboBox<>();
        fname = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        showpass = new javax.swing.JCheckBox();
        jLabel23 = new javax.swing.JLabel();
        nu = new javax.swing.JTextField();
        ULform1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        header9 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Unavbar.setBackground(new java.awt.Color(255, 255, 255));
        Unavbar.setForeground(new java.awt.Color(102, 102, 102));
        Unavbar.setLayout(null);

        cancel.setBackground(new java.awt.Color(255, 51, 51));
        cancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cancel.setForeground(new java.awt.Color(255, 255, 255));
        cancel.setText("Cancel");
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
        });
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        Unavbar.add(cancel);
        cancel.setBounds(60, 290, 100, 37);

        lastname.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lastname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lastname.setText("Last Name:");
        Unavbar.add(lastname);
        lastname.setBounds(170, 40, 90, 17);

        login1.setBackground(new java.awt.Color(0, 204, 255));
        login1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        login1.setForeground(new java.awt.Color(255, 255, 255));
        login1.setText("Register");
        login1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login1ActionPerformed(evt);
            }
        });
        Unavbar.add(login1);
        login1.setBounds(180, 290, 100, 37);

        lname.setBackground(new java.awt.Color(204, 204, 204));
        lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameActionPerformed(evt);
            }
        });
        Unavbar.add(lname);
        lname.setBounds(170, 60, 170, 30);

        jpanelEmail.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jpanelEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jpanelEmail.setText("Email:");
        Unavbar.add(jpanelEmail);
        jpanelEmail.setBounds(170, 160, 50, 17);

        em.setBackground(new java.awt.Color(204, 204, 204));
        em.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emActionPerformed(evt);
            }
        });
        Unavbar.add(em);
        em.setBounds(170, 180, 170, 30);

        username1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        username1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        username1.setText("User Name:");
        Unavbar.add(username1);
        username1.setBounds(10, 100, 80, 17);

        uname.setBackground(new java.awt.Color(204, 204, 204));
        uname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unameActionPerformed(evt);
            }
        });
        Unavbar.add(uname);
        uname.setBounds(10, 120, 150, 30);

        username.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        username.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        username.setText("Password:");
        Unavbar.add(username);
        username.setBounds(0, 220, 100, 20);

        usertype.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        usertype.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usertype.setText("User Type:");
        Unavbar.add(usertype);
        usertype.setBounds(170, 100, 80, 20);

        firstname.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        firstname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        firstname.setText("First Name:");
        Unavbar.add(firstname);
        firstname.setBounds(10, 40, 90, 17);

        ut.setBackground(new java.awt.Color(204, 204, 204));
        ut.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ut.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select UserType", "User", "Admin" }));
        Unavbar.add(ut);
        ut.setBounds(170, 120, 170, 30);

        fname.setBackground(new java.awt.Color(204, 204, 204));
        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });
        Unavbar.add(fname);
        fname.setBounds(10, 60, 150, 30);

        password.setBackground(new java.awt.Color(204, 204, 204));
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        Unavbar.add(password);
        password.setBounds(10, 240, 150, 30);

        showpass.setText("Show Password");
        showpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpassActionPerformed(evt);
            }
        });
        Unavbar.add(showpass);
        showpass.setBounds(170, 240, 120, 30);

        jLabel23.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel23.setText("Contact #:");
        Unavbar.add(jLabel23);
        jLabel23.setBounds(10, 160, 70, 20);

        nu.setBackground(new java.awt.Color(204, 204, 204));
        Unavbar.add(nu);
        nu.setBounds(10, 180, 150, 30);

        getContentPane().add(Unavbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 345, 360));

        ULform1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        ULform1.setForeground(new java.awt.Color(255, 204, 0));
        ULform1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ULform1.setText("REGISTRATION FORM");
        ULform1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(ULform1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 750, 50));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pet.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 300, 380));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/backgound (1) (1).png"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 710, 440));

        header9.setBackground(new java.awt.Color(0, 51, 102));
        header9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                header9MouseClicked(evt);
            }
        });
        header9.setLayout(null);
        getContentPane().add(header9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
        Login lg = new Login();
        lg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelMouseClicked

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed

    }//GEN-LAST:event_cancelActionPerformed

    private void login1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login1ActionPerformed

        

        if

        (fname.getText().isEmpty() || lname.getText().isEmpty()
            || em.getText().isEmpty()
            || ut.getSelectedIndex()==0
            || uname.getText().isEmpty()
            ||nu.getText().isEmpty()
            || password.getText().isEmpty() ){
            JOptionPane.showMessageDialog(null,"All fields are required!"); //validation for register...

            return ;

        }else if (password.getText().length()< 8){
            JOptionPane.showMessageDialog(null," Password should contain atleast 8 character above!");
            password.setText("");
            return;}

        String email = em.getText();
        String emailRegex = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$";
        Pattern patternEmail = Pattern.compile(emailRegex);
        Matcher matcherEmail = patternEmail.matcher(email);

        if (!matcherEmail.matches()) {
            JOptionPane.showMessageDialog(this, "Invalid email format. Please use a valid email address.", "Error", JOptionPane.ERROR_MESSAGE);
            em.setText("");
            em.requestFocus();

        }

        else if(duplicateCheck()){
            System.out.println("Duplicate Exist!");
      
        }
        else {
              dbConnect dbc=new dbConnect();
            
            try {
            String pass=passwordHasher.hashPassword(password.getText());
        
        if (dbc.insertData("INSERT INTO accounts(firstname, lastname, email, type, username, password, contact, status) "
        + "VALUES('"+fname.getText()+"',"
        + "'"+lname.getText()+"',"
        + "'"+em.getText()+"',"
        + "'"+ut.getSelectedItem()+"',"
        + "'"+uname.getText()+"',"
        + "'"+ pass+"'," 
        + "'"+nu.getText()+"','Pending')") == 1)
{
        JOptionPane.showMessageDialog(null, "Succesfully Register");
        Login lg = new Login();
        lg.show();
        this.dispose();

        } else {
            JOptionPane.showMessageDialog(null,"Connection error!!");
        }
    }catch(NoSuchAlgorithmException ex){
                System.out.println(""+ex);
                }
    }//GEN-LAST:event_login1ActionPerformed
    }
    private void lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameActionPerformed

    private void emActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emActionPerformed

    }//GEN-LAST:event_emActionPerformed

    private void unameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unameActionPerformed

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void header9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_header9MouseClicked

    }//GEN-LAST:event_header9MouseClicked

    private void showpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpassActionPerformed

        if (showpass.isSelected()){
            password.setEchoChar((char)0);
        }else{
            password.setEchoChar('*');
        }

    }//GEN-LAST:event_showpassActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ULform1;
    private javax.swing.JPanel Unavbar;
    private javax.swing.JButton cancel;
    private javax.swing.JTextField em;
    private javax.swing.JLabel firstname;
    private javax.swing.JTextField fname;
    private javax.swing.JPanel header9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jpanelEmail;
    private javax.swing.JLabel lastname;
    private javax.swing.JTextField lname;
    private javax.swing.JButton login1;
    private javax.swing.JTextField nu;
    private javax.swing.JPasswordField password;
    private javax.swing.JCheckBox showpass;
    private javax.swing.JTextField uname;
    private javax.swing.JLabel username;
    private javax.swing.JLabel username1;
    private javax.swing.JLabel usertype;
    private javax.swing.JComboBox<String> ut;
    // End of variables declaration//GEN-END:variables
}
